# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
    ]
